// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Note struct {
	SerialID  int32
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamp
	Title     string
	Text      string
}
