// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: notes_select.sql

package db

import (
	"context"
)

const selectNotes = `-- name: SelectNotes :many

SELECT
  serial_id, id, created_at, title, text
FROM
    notes
ORDER BY
    created_at DESC
`

func (q *Queries) SelectNotes(ctx context.Context) ([]Note, error) {
	rows, err := q.db.Query(ctx, selectNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.SerialID,
			&i.ID,
			&i.CreatedAt,
			&i.Title,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
