// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: notes_delete.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteNote = `-- name: DeleteNote :one

DELETE FROM
    notes n
WHERE
    n.id = $1
RETURNING
    n.serial_id
`

func (q *Queries) DeleteNote(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, deleteNote, id)
	var serial_id int32
	err := row.Scan(&serial_id)
	return serial_id, err
}
