// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: notes_update.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateNoteBySerialID = `-- name: UpdateNoteBySerialID :one
UPDATE
    notes n
SET
    title = CASE WHEN $1::boolean
        THEN $2::TEXT ELSE title END,
    text = CASE WHEN $3::boolean
        THEN $4::TEXT ELSE text END
WHERE
    n.id = $5
RETURNING
    n.serial_id
`

type UpdateNoteBySerialIDParams struct {
	TitleDoUpdate bool
	Title         string
	TextDoUpdate  bool
	Text          string
	NoteID        pgtype.UUID
}

func (q *Queries) UpdateNoteBySerialID(ctx context.Context, arg UpdateNoteBySerialIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateNoteBySerialID,
		arg.TitleDoUpdate,
		arg.Title,
		arg.TextDoUpdate,
		arg.Text,
		arg.NoteID,
	)
	var serial_id int32
	err := row.Scan(&serial_id)
	return serial_id, err
}
