// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	DeleteNote(ctx context.Context, id pgtype.UUID) (int32, error)
	InsertNote(ctx context.Context, arg InsertNoteParams) (int32, error)
	SelectNotes(ctx context.Context) ([]Note, error)
	UpdateNoteBySerialID(ctx context.Context, arg UpdateNoteBySerialIDParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
